<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701073329 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align database schema with Doctrine DBAL 4 and Symfony 8.1';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('COMMENT ON COLUMN clients.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN clients.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN clients.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN expense_categories.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN expense_categories.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN expense_categories.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN orders.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN orders.client_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN orders.order_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN orders.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN orders.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN trucks.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN trucks.manufacture_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN trucks.purchase_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN trucks.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN trucks.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'\'');

        $this->migrateTransportTable('messenger_messages', 'idx_75ea56e0fb7336f0', 'idx_75ea56e016ba31db', 'idx_75ea56e0e3bd61ce', 'IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->migrateTransportTable('scheduler_messages', 'idx_8067ade6fb7336f0', 'idx_8067ade616ba31db', 'idx_8067ade6e3bd61ce', 'IDX_8067ADE6FB7336F0E3BD61CE16BA31DBBF396750');
    }

    public function down(Schema $schema): void
    {
        $this->revertTransportTable('messenger_messages', 'idx_75ea56e0fb7336f0', 'idx_75ea56e016ba31db', 'idx_75ea56e0e3bd61ce', 'IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->revertTransportTable('scheduler_messages', 'idx_8067ade6fb7336f0', 'idx_8067ade616ba31db', 'idx_8067ade6e3bd61ce', 'IDX_8067ADE6FB7336F0E3BD61CE16BA31DBBF396750');

        $this->addSql('COMMENT ON COLUMN clients.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN clients.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN clients.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN expense_categories.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN expense_categories.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN expense_categories.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN orders.order_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN orders.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN orders.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN orders.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN orders.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN trucks.manufacture_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN trucks.purchase_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN trucks.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN trucks.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN trucks.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
    }

    private function migrateTransportTable(
        string $table,
        string $queueIndex,
        string $deliveredIndex,
        string $availableIndex,
        string $compositeIndex,
    ): void {
        $this->addSql(sprintf('DROP INDEX %s', $queueIndex));
        $this->addSql(sprintf('DROP INDEX %s', $deliveredIndex));
        $this->addSql(sprintf('DROP INDEX %s', $availableIndex));
        $this->addSql(sprintf('ALTER TABLE %s ALTER id DROP DEFAULT', $table));
        $this->addSql(sprintf('ALTER TABLE %s ALTER id ADD GENERATED BY DEFAULT AS IDENTITY', $table));
        $this->addSql(sprintf('COMMENT ON COLUMN %s.created_at IS \'\'', $table));
        $this->addSql(sprintf('COMMENT ON COLUMN %s.available_at IS \'\'', $table));
        $this->addSql(sprintf('COMMENT ON COLUMN %s.delivered_at IS \'\'', $table));
        $this->addSql(sprintf('CREATE INDEX %s ON %s (queue_name, available_at, delivered_at, id)', $compositeIndex, $table));
    }

    private function revertTransportTable(
        string $table,
        string $queueIndex,
        string $deliveredIndex,
        string $availableIndex,
        string $compositeIndex,
    ): void {
        $this->addSql(sprintf('DROP INDEX %s', $compositeIndex));
        $this->addSql(sprintf('ALTER TABLE %s ALTER id SET DEFAULT nextval(\'%s_id_seq\'::regclass)', $table, $table));
        $this->addSql(sprintf('ALTER TABLE %s ALTER id DROP IDENTITY', $table));
        $this->addSql(sprintf('COMMENT ON COLUMN %s.created_at IS \'(DC2Type:datetime_immutable)\'', $table));
        $this->addSql(sprintf('COMMENT ON COLUMN %s.available_at IS \'(DC2Type:datetime_immutable)\'', $table));
        $this->addSql(sprintf('COMMENT ON COLUMN %s.delivered_at IS \'(DC2Type:datetime_immutable)\'', $table));
        $this->addSql(sprintf('CREATE INDEX %s ON %s (queue_name)', $queueIndex, $table));
        $this->addSql(sprintf('CREATE INDEX %s ON %s (delivered_at)', $deliveredIndex, $table));
        $this->addSql(sprintf('CREATE INDEX %s ON %s (available_at)', $availableIndex, $table));
    }
}
