[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisor/supervisord.pid
user=%(ENV_USER_NAME)s

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:messenger-scheduler]
command=php bin/console messenger:consume scheduler_default -vv
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=APP_ENV=%(ENV_APP_ENV)s,MESSENGER_CONSUMER_NAME=scheduler-worker

[program:messenger-async]
command=php bin/console messenger:consume async -vv
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=APP_ENV=%(ENV_APP_ENV)s,MESSENGER_CONSUMER_NAME=async-worker

[program:scheduler-weekly-order-report-worker]
command=php bin/console messenger:consume scheduler_weekly_order_report -vv
directory=/var/www
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=APP_ENV=%(ENV_APP_ENV)s,MESSENGER_CONSUMER_NAME=scheduler-weekly-order-report-worker
